# This is required for the recipe to build on aarch64
arm_variant_type: # [aarch64]
  - sbsa          # [aarch64]

# Use latest CUDA 12.x and 13.x
cuda_compiler_version:
  - 12.8
  - 13.0

# Use compatible libcublas versions for each CUDA version
libcublas:
  - 12
  - 13

zip_keys:
  -
    - cuda_compiler_version
    - libcublas
